FSMA-8FSMA-88_fix_product_creation_issue
fiterafrica/community-app-template pull request #304
Opened 2024-04-05 14:31 UTC by Deepika1095

https://fiterio.atlassian.net/browse/FSMA-88

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2024-04-05 15:37 UTC, Napho requested changes

2024-04-05 15:37 UTC, Napho commented on app/scripts/controllers/product/CreateLoanProductController.js
> +            console.log(this.formData);
I think you forgot to remove the logs

2024-04-05 15:37 UTC, Napho commented on app/scripts/controllers/product/CreateLoanProductController.js
> +                console.log(this.formData, "inend");
and this too

2024-04-08 06:54 UTC, Deepika1095 commented on app/scripts/controllers/product/CreateLoanProductController.js
> +            console.log(this.formData);
ahh sorry I will do that.

2024-04-08 08:09 UTC, oluexpert99 approved these changes, later dismissed
LGTM

2024-04-08 09:52 UTC, Napho approved these changes

2024-04-08 10:37 UTC, hero78 approved these changes

2024-04-08 10:39 UTC, merged