CI18-128 - Adding Savings and Deposit Types and Categories
fiterafrica/community-app-template pull request #31
Opened 2023-03-20 10:09 UTC by jumba2010

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2023-03-20 11:04 UTC, hagafrank requested changes
The spacing used is hard on the eyes. Could you at least leave space between on either side of the operators. So something like this

`scope.savingproduct.productCategory=productCategory?productCategory.name:'';`

should be changed to this:

`scope.savingproduct.productCategory = productCategory ? productCategory.name : '';`

2023-03-20 11:04 UTC, hagafrank commented on app/scripts/controllers/product/CreateFixedDepositProductController.js
> +                scope.productCategories=data.productCategories;
Can we have better spacing here?

2023-03-20 11:20 UTC, Napho approved these changes, later dismissed

2023-03-20 12:42 UTC, hagafrank submitted a review, later dismissed

2023-03-22 10:54 UTC, hero78 approved these changes
LGTM

2023-03-22 11:00 UTC, hagafrank approved these changes

2023-03-22 11:00 UTC, merged