INKO-46 - Managing Client Household Expenses
fiterafrica/community-app-template pull request #87
Opened 2023-07-07 20:06 UTC by jumba2010

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2023-07-11 12:39 UTC, hero78 requested changes

2023-07-11 12:39 UTC, hero78 commented on app/scripts/routes.js
> +                        })
These looks to be part of the client directory not admin ?

2023-07-11 12:39 UTC, hero78 commented on app/views/administration/EditExpenses.html
> +    <form name="FieldConfiguration" novalidate="" class="form-horizontal well" >
file should be moved to client's folder

2023-07-11 12:39 UTC, hero78 commented on app/views/administration/AddExpenses.html
> +<div ng-controller="AddExpensesController">
file should be moved to client's folder

2023-07-12 06:52 UTC, hero78 approved these changes, later dismissed
LGTM

2023-07-12 07:28 UTC, Deepika1095 approved these changes, later dismissed

2023-07-12 08:00 UTC, Deepika1095 approved these changes

2023-07-12 08:00 UTC, hero78 approved these changes

2023-07-12 08:00 UTC, merged